CREATE TABLE `data_fetch_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fetchType` varchar(32) NOT NULL,
	`targetDate` date,
	`stadiumId` varchar(2),
	`raceNumber` tinyint,
	`status` varchar(16) NOT NULL,
	`rowsAffected` int,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `data_fetch_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prediction_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`raceDate` date NOT NULL,
	`stadiumId` varchar(2) NOT NULL,
	`raceNumber` tinyint NOT NULL,
	`predictions` json NOT NULL,
	`modelVersion` varchar(32),
	`actualResult` varchar(10),
	`isHit` tinyint,
	`payout` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `prediction_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `race_before_info` (
	`id` int AUTO_INCREMENT NOT NULL,
	`raceDate` date NOT NULL,
	`stadiumId` varchar(2) NOT NULL,
	`raceNumber` tinyint NOT NULL,
	`boatNumber` tinyint NOT NULL,
	`exhibitionTime` float,
	`circuitTime` float,
	`tilt` float,
	`trifectaOdds` json,
	`winOdds` float,
	`startCourse` tinyint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `race_before_info_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `race_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`raceDate` date NOT NULL,
	`stadiumId` varchar(2) NOT NULL,
	`raceNumber` tinyint NOT NULL,
	`boatNumber` tinyint NOT NULL,
	`racerNumber` int,
	`racerName` varchar(64),
	`racerClass` varchar(4),
	`age` tinyint,
	`weight` float,
	`branch` varchar(32),
	`birthPlace` varchar(32),
	`nationalWinRate` float,
	`national2Rate` float,
	`national3Rate` float,
	`localWinRate` float,
	`local2Rate` float,
	`motorNumber` int,
	`motor2Rate` float,
	`motor3Rate` float,
	`boatNumber2` int,
	`boat2Rate` float,
	`avgSt` float,
	`flyingCount` tinyint,
	`lateCount` tinyint,
	`sessionResults` varchar(64),
	`weather` varchar(16),
	`windDirection` varchar(16),
	`windSpeed` float,
	`waveHeight` float,
	`waterTemp` float,
	`airTemp` float,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `race_entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `race_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`raceDate` date NOT NULL,
	`stadiumId` varchar(2) NOT NULL,
	`raceNumber` tinyint NOT NULL,
	`boatNumber` tinyint NOT NULL,
	`place` tinyint,
	`racerNumber` int,
	`startTiming` float,
	`trifectaCombo` varchar(10),
	`trifectaPayout` int,
	`exactaCombo` varchar(10),
	`exactaPayout` int,
	`trioCombo` varchar(10),
	`trioPayout` int,
	`quinellaCombo` varchar(10),
	`quinellaPayout` int,
	`winCombo` varchar(5),
	`winPayout` int,
	`placeCombo` varchar(5),
	`placePayout` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `race_results_id` PRIMARY KEY(`id`)
);
